// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnysoIq2Fi2GW6MyBFtVW6b6MYwuj5p2U',
    appId: '1:101548064324:android:0d0ff13fb6d9a7bdd30611',
    messagingSenderId: '101548064324',
    projectId: 'doador-sangue-44331',
    storageBucket: 'doador-sangue-44331.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIrndgDBMP7T3-hZ8YJI99nwsujispviI',
    appId: '1:101548064324:ios:42092ae526563e10d30611',
    messagingSenderId: '101548064324',
    projectId: 'doador-sangue-44331',
    storageBucket: 'doador-sangue-44331.firebasestorage.app',
    iosBundleId: 'com.example.doadorSangue2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC48QeEFEfhRzaLK5zrs9Vguc6f26sF-BQ',
    appId: '1:101548064324:web:875030744d08cb5cd30611',
    messagingSenderId: '101548064324',
    projectId: 'doador-sangue-44331',
    authDomain: 'doador-sangue-44331.firebaseapp.com',
    storageBucket: 'doador-sangue-44331.firebasestorage.app',
    measurementId: 'G-S83C18JGRC',
  );

}